# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                    BiomeDodgeball                                            | #
# |                                                                                              | #
# |                                                                                              | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #

stats:
  uuid:
    thrown: 10
