# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                    BiomeDodgeball                                            | #
# |                                                                                              | #
# |                       https://github.com/biomepw/BiomeDodgeball                              | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #
red:
  spawn_location: world,1,2,3

blue:
  spawn_location: world,1,2,3

lobby:
  spawn_location: world,1,2,3

spectator:
  locations: []